# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be24e1c47e6a6a2d50abee10be0a90ae509a5d1a544d005a0cdc4e5390761f02c3e2667c787cb7a81b999cc0847cb0207d3a9fc6bf074f17f72219d4aaa7d8c5

test:
  secret_key_base: f8d1543382c0d58a3de2da4ca4754c7e69d5cb1486dfcc4c75f441b8d9ac4401e33abd020b125c882e8c7eb0b3d44c1ec10b15d997e6dd69b38b9820abd6b9ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
